name: GestionContrats
version: ${project.version}
main: com.vincent.gestionContrats.GestionContrats
api-version: '1.20'
depend: [Vault]
commands:
  contrats:
    description: Gérer les contrats disponibles
    usage: /contrats consulter | /contrats accepter | /contrats suppression | /contrats confirmer-suppression | /contrats lister
